name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.6.0
      with:
        project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
        credentials: ${{ secrets.GCLOUD_CREDENTIALS }}

    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy price-service-java \
          --source . \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated
